linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gomnd
    - gomoddirectives
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace

linters-settings:
  forbidigo:
    forbid:
      - fmt.Errorf
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  lll:
    line-length: 132

run:
  skip-files:
    - internal/pkg/assets/statik.go
