builds:
  - id: couture
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: pandich
    name: couture

brews:
  - name: couture
    tap:
      owner: pandich
      name: couture
    folder: Formula
    description: "Allows for tailing multiple event sources."
