# TODO finish layout implementation
application:
  width: 25
  sigil: §
caller:
  width: 60
  sigil: ☎
level:
  width: 1
message:
source:
  width: 40
context:
  width: 20
  sigil: ⇶
timestamp:
  sigil: ☀
