[logstash]
format = "json"
priority = 100
[logstash.predicates]
"@version" = "^1$"
[logstash.mapping]
timestamp = "@timestamp"
level = "level"
application = "application"
thread = "thread_name"
class = "class"
method = "method"
line = "line_number"
message = "message"
exception = "exception.stacktrace"

[aws-billing-report]
format = "text"
priority = 90
[aws-billing-report.predicates]
"_" = "^(?P<message>REPORT RequestId: (?P<thread>\\S+)\\s+.+)$"

[aws-billing-start]
format = "text"
priority = 90
[aws-billing-start.predicates]
"_" = "^(?P<message>START RequestId:\\s+(?P<thread>\\S+).+)$"

[aws-billing-end]
format = "text"
priority = 90
[aws-billing-end.predicates]
"_" = "^(?P<message>END RequestId: (?P<thread>.+))$"
