# TODO @Jim fix any problems in here, and add missing formats
#   see:  parser_*.rb definitions in https://github.com/fluent/fluentd/tree/master/lib/fluent/plugin
#         https://docs.fluentd.org/v/0.12/articles/common-log-formats
#   see:  more format info in https://www.graylog.org/post/log-formats-a-complete-guide

# FEATURE json should allow composite fields. change it to interpolation
#   Example: class = "${fieldA}/${fieldB}"

[logstash]
format = "json"
priority = 100
[logstash.predicates]
"@version" = "^1$"
[logstash.mapping]
timestamp = "@timestamp"
level = "level"
application = "application"
thread = "thread_name"
class = "class"
method = "method"
line = "line_number"
message = "message"
exception = "exception.stacktrace"

[cloudwatch-event]
format = "json"
priority = 90
[cloudwatch-event.predicates]
"tag" = "^cloud-watch$"
"eventVersion" = "^1\\.\\d+$"
[cloudwatch-event.mapping]
timestamp = "@timestamp"
application = "tag"
thread = "id"
class = "logGroup"
method = "logStream"
message = "log"
exception = "exception.stacktrace"

[aws-billing-report]
format = "text"
priority = 90
[aws-billing-report.predicates]
_ = "^(?P<message>REPORT (?P<class>RequestId):\\s+(?P<method>\\S+)\\s+.+)(?P<level>)(?P<thread>)(?P<line>)(?P<application>)(?P<timestamp>)(?P<exception>)$"

[aws-billing-start]
format = "text"
priority = 90
[aws-billing-start.predicates]
_ = "^(?P<message>START (?P<class>RequestId):(?P<method>\\s+\\S+).+)(?P<level>)(?P<thread>)(?P<line>)(?P<application>)(?P<timestamp>)(?P<exception>)$"

[aws-billing-end]
format = "text"
priority = 90
[aws-billing-end.predicates]
_ = "^(?P<message>END (?P<class>RequestId):\\s+(?P<method>\\S+)\\s+.+)(?P<level>)(?P<thread>)(?P<line>)(?P<application>)(?P<timestamp>)(?P<exception>)$"
