[logstash]
priority = 100
predicates."@version " = "^1$"
mapping.timestamp = "@timestamp"
mapping.level = "level"
mapping.application = "application"
mapping.thread = "thread_name"
mapping.class = "class"
mapping.method = "method"
mapping.line = "line_number"
mapping.message = "message"
mapping.exception = "exception.stacktrace"
