[logstash]
format = "json"
priority = 100
[logstash.predicates]
"@version" = "^1$"
[logstash.mapping]
timestamp = "@timestamp"
level = "level"
application = "application"
thread = "thread_name"
class = "class"
method = "method"
line = "line_number"
message = "message"
exception = "exception.stacktrace"

[aws-billing-report]
format = "text"
priority = 90
[aws-billing-report.predicates]
"_" = "^(?P<message>REPORT (?P<class>RequestId):\\s+(?P<method>\\S+)\\s+.+)(?P<level>)(?P<thread>)(?P<line>)(?P<application>)(?P<timestamp>)(?P<exception>)$"

[aws-billing-start]
format = "text"
priority = 90
[aws-billing-start.predicates]
"_" = "^(?P<message>START (?P<class>RequestId):(?P<method>\\s+\\S+).+)(?P<level>)(?P<thread>)(?P<line>)(?P<application>)(?P<timestamp>)(?P<exception>)$"

[aws-billing-end]
format = "text"
priority = 90
[aws-billing-end.predicates]
"_" = "^(?P<message>END (?P<class>RequestId):\\s+(?P<method>\\S+)\\s+.+)(?P<level>)(?P<thread>)(?P<line>)(?P<application>)(?P<timestamp>)(?P<exception>)$"
